### ISSUE TITLE
Add button for slides

### ISSUE THREAD

**Issue by dhawal27** [kulstuff/ninjaproject#21]
no need of syllabus button right??

**Comment by shreyanshrana** [comment]
its needed.

for syllabus.pdf and marks distribution

**Comment by dhawal27** [comment]
what about slides??

**Comment by shreyanshrana** [comment]
slides and notes will be separate. so yeah it is needed

**Comment by dhawal27** [comment]
for syllabus and marks distribution we have course site

**Comment by dhawal27** [comment]
notes and slides will have one button
