### ISSUE TITLE
span tag code readability

### ISSUE THREAD

**Issue by Aadiyaara** [kulstuff/ninjaproject#24]
If I intend the span tags properly in landing year btns, spaces are generated between the text letters, this is currently avoided but the readability of code is compromised. Display: inline-block isn't working for those span tags as well

**Comment by shreyanshrana** [comment]
I've changed the code to use background clip thus removing all span tags.
Adding this code to any text with background image of element set by linear-gradient()
`-webkit-background-clip:text;`
`color:transparent;`

If satisfied, close the issue
